dbt_profile1:  # your profile name from dbt_project.yml
  target: dev  # your development environment
  outputs:
    
    dev:
      type: bigquery
      method: service-account
      project: first-demo-361604  # name of the project in BigQuery
      dataset: dbt_demo_bigquery  # your dataset for development (usually your name)
      threads: 4
      keyfile: /secrets/dbt-service-keyfile
      timeout_seconds: 3600
      priority: interactive
      retries: 3

