
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: artists
            description: "The artists"
          - name: track_id
            description: "The track id"
          - name: track_link
            description: "The link"
          - name: track_name
            description: "The track name"